### ISSUE TITLE
S3 bucket access denied

### ISSUE THREAD

**Issue by MauriSalazar** [dwyl/image-uploads#3]
I'm having issues with the config.json file I think (credentials or permissions).

This is the error I'm getting on the frontend side:

![image](https://cloud.githubusercontent.com/assets/4121898/3525468/2e7f6e06-0773-11e4-954f-bedfe8cb83d9.png)

This one on Meteor console:

![image](https://cloud.githubusercontent.com/assets/4121898/3525482/4e256bc0-0773-11e4-8e4d-c3c1293f409a.png)

If I try loading the link that gave an error on the frontend I get this:

Imágenes integradas 3
![image](https://cloud.githubusercontent.com/assets/4121898/3525496/71434ad2-0773-11e4-9204-0f37ac396082.png)

S3 account:

![image](https://cloud.githubusercontent.com/assets/4121898/3525504/86dc68ce-0773-11e4-83d8-e4b79902fdc0.png)

config.json file on the App:

![image](https://cloud.githubusercontent.com/assets/4121898/3525510/96aa5f86-0773-11e4-859f-3fd33a3318a6.png)

I gave a bucket policy for testingboris since I was getting denied error but didn't do the trick:

![image](https://cloud.githubusercontent.com/assets/4121898/3525527/a842e574-0773-11e4-99ae-33346107621a.png)

![image](https://cloud.githubusercontent.com/assets/4121898/3525572/2853fa50-0774-11e4-8ded-71a970f6c526.png)

It seems to be a permission issue with the bucket.

Another thing I had to do with the project was to change require() to Meteor.require if not I got an error on console. (require is not defined).

Really Appreciate some help on this!

**Comment by nelsonic** [comment]
@MauriSalazar guessing you got this working?

**Comment by nelsonic** [comment]
If this is still an issue, please raise it here: https://github.com/ideaq/image-uploads
