### ISSUE TITLE
Updating the SDK example: how much public access should be granted?

### ISSUE THREAD

**Issue by Cleop** [dwyl/image-uploads#41]
**I am getting this warning whilst following the SDK example:**

![image](https://user-images.githubusercontent.com/16775804/47714191-201d4780-dc34-11e8-9288-d956c31b1257.png)

**I chose the following access permissions:**
![image](https://user-images.githubusercontent.com/16775804/47714265-54910380-dc34-11e8-8ef5-d9e486b82695.png)

**Based on the guidance from this step of the existing tutorial:**

![image](https://user-images.githubusercontent.com/16775804/47714334-78ece000-dc34-11e8-82c7-6095a7f57480.png)

I wanted to get a second opinion on whether I had interpreted the updated version of the steps correctly and therefore whether I should react to this warning message?

**Comment by nelsonic** [comment]
@Cleop what problem are you trying to solve? 
and does that problem _require_ giving access to the uploaded images to _everyone_...?

**Comment by Cleop** [comment]
The problem we are trying to solve is to create a file system for a public site. Therefore in this context I imagine that having the files available to the public is not of concern as they will already be visible on the website anyway. None of the data is personal or private data. If we were to place restrictions on access to the data in S3 we might then have to remove those permissions in order to display the content on the public site which would be an unnecessary step. 

So thanks for clarifying, I think despite the warning we are in a safe position to ignore it and I add a note on this in the readme so people can decide what is right for their particular use case 😊

**Comment by Cleop** [comment]
I am now updating the readme to reflect these changes and updates in the existing AWS flow

**Comment by nelsonic** [comment]
@Cleop thank you for updating the docs! 👍

**Comment by Cleop** [comment]
Closing as this has now been merged
